[package]
name = "kfp-sdk"
version = "0.1.0"
authors = ["André Claudino <claudino@d2x.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.7"
